import { ClassData } from '../types/gradebook';

export const INITIAL_CLASSES: ClassData[] = [
  {
    id: 'class-1',
    name: 'Grade 10 - Mathematics',
    gradeLevel: '10th Grade',
    academicYear: '2026-2027',
    subject: 'Algebra & Geometry',
    categories: [
      { id: 'att', name: 'Attendance', defaultCap: 5, color: '#10b981' },
      { id: 'part', name: 'Participation', defaultCap: 10, color: '#6366f1' },
      { id: 'hw', name: 'Homework', defaultCap: 10, color: '#f59e0b' },
    ],
    months: [
      { id: 'sep', name: 'September', shortName: 'Sep', academicYear: '2026-2027' },
      { id: 'oct', name: 'October', shortName: 'Oct', academicYear: '2026-2027' },
      { id: 'nov', name: 'November', shortName: 'Nov', academicYear: '2026-2027' },
    ],
    lessons: [
      // September Lessons
      { id: 'sep-l1', monthId: 'sep', dayNumber: 1, date: 'Sep 02', title: 'Day 1' },
      { id: 'sep-l2', monthId: 'sep', dayNumber: 2, date: 'Sep 05', title: 'Day 2' },
      { id: 'sep-l3', monthId: 'sep', dayNumber: 3, date: 'Sep 09', title: 'Day 3' },
      { id: 'sep-l4', monthId: 'sep', dayNumber: 4, date: 'Sep 12', title: 'Day 4' },

      // October Lessons
      { id: 'oct-l1', monthId: 'oct', dayNumber: 5, date: 'Oct 03', title: 'Day 5' },
      { id: 'oct-l2', monthId: 'oct', dayNumber: 6, date: 'Oct 07', title: 'Day 6' },
      { id: 'oct-l3', monthId: 'oct', dayNumber: 7, date: 'Oct 10', title: 'Day 7' },
      { id: 'oct-l4', monthId: 'oct', dayNumber: 8, date: 'Oct 14', title: 'Day 8' },

      // November Lessons
      { id: 'nov-l1', monthId: 'nov', dayNumber: 9, date: 'Nov 04', title: 'Day 9' },
      { id: 'nov-l2', monthId: 'nov', dayNumber: 10, date: 'Nov 07', title: 'Day 10' },
      { id: 'nov-l3', monthId: 'nov', dayNumber: 11, date: 'Nov 11', title: 'Day 11' },
      { id: 'nov-l4', monthId: 'nov', dayNumber: 12, date: 'Nov 14', title: 'Day 12' },
    ],
    students: [
      { id: 's1', name: 'Alexander Wright', rollNo: '101', email: 'alex.w@school.edu', notes: 'Very active in discussions' },
      { id: 's2', name: 'Beatrice Chen', rollNo: '102', email: 'beatrice.c@school.edu', notes: 'Consistently completes all homework' },
      { id: 's3', name: 'Carlos Mendez', rollNo: '103', email: 'carlos.m@school.edu', notes: 'Gained momentum in October' },
      { id: 's4', name: 'Diana Morales', rollNo: '104', email: 'diana.m@school.edu', notes: 'Missed some homework on Day 3' },
      { id: 's5', name: 'Ethan Patel', rollNo: '105', email: 'ethan.p@school.edu', notes: 'Diligent attendance' },
      { id: 's6', name: 'Fiona Gallagher', rollNo: '106', email: 'fiona.g@school.edu', notes: 'Great classroom contributor' },
      { id: 's7', name: 'George Kim', rollNo: '107', email: 'george.k@school.edu', notes: 'Steady average across lessons' },
    ],
    grades: {
      s1: {
        'sep-l1': { att: 5, part: 9, hw: 9 },  // 23/25 = 92%
        'sep-l2': { att: 5, part: 9, hw: 10 }, // 24/25 = 96%
        'sep-l3': { att: 5, part: 8, hw: 9 },  // 22/25 = 88%
        'sep-l4': { att: 5, part: 10, hw: 10 },// 25/25 = 100%
        'oct-l1': { att: 5, part: 10, hw: 10 },
        'oct-l2': { att: 5, part: 9, hw: 10 },
        'oct-l3': { att: 5, part: 10, hw: 9 },
        'oct-l4': { att: 5, part: 10, hw: 10 },
        'nov-l1': { att: 5, part: 9, hw: 10 },
        'nov-l2': { att: 5, part: 10, hw: 10 },
        'nov-l3': { att: 5, part: 9, hw: 9 },
        'nov-l4': { att: 5, part: 10, hw: 10 },
      },
      s2: {
        'sep-l1': { att: 5, part: 10, hw: 10 },
        'sep-l2': { att: 5, part: 10, hw: 10 },
        'sep-l3': { att: 5, part: 10, hw: 10 },
        'sep-l4': { att: 5, part: 10, hw: 9 },
        'oct-l1': { att: 5, part: 10, hw: 10 },
        'oct-l2': { att: 5, part: 10, hw: 10 },
        'oct-l3': { att: 5, part: 10, hw: 10 },
        'oct-l4': { att: 5, part: 10, hw: 10 },
        'nov-l1': { att: 5, part: 10, hw: 10 },
        'nov-l2': { att: 5, part: 10, hw: 10 },
        'nov-l3': { att: 5, part: 10, hw: 10 },
        'nov-l4': { att: 5, part: 10, hw: 10 },
      },
      s3: {
        'sep-l1': { att: 4, part: 6, hw: 5 },
        'sep-l2': { att: 4, part: 6, hw: 6 },
        'sep-l3': { att: 5, part: 7, hw: 7 },
        'sep-l4': { att: 5, part: 8, hw: 8 },
        'oct-l1': { att: 5, part: 8, hw: 8 },
        'oct-l2': { att: 5, part: 9, hw: 9 },
        'oct-l3': { att: 5, part: 9, hw: 9 },
        'oct-l4': { att: 5, part: 9, hw: 10 },
        'nov-l1': { att: 5, part: 9, hw: 9 },
        'nov-l2': { att: 5, part: 10, hw: 10 },
        'nov-l3': { att: 5, part: 9, hw: 9 },
        'nov-l4': { att: 5, part: 10, hw: 10 },
      },
      s4: {
        'sep-l1': { att: 5, part: 9, hw: 9 },
        'sep-l2': { att: 5, part: 8, hw: 9 },
        'sep-l3': { att: 3, part: 5, hw: 4 }, // drop on Day 3
        'sep-l4': { att: 4, part: 7, hw: 7 },
        'oct-l1': { att: 5, part: 8, hw: 8 },
        'oct-l2': { att: 5, part: 9, hw: 9 },
        'oct-l3': { att: 5, part: 8, hw: 9 },
        'oct-l4': { att: 5, part: 9, hw: 9 },
        'nov-l1': { att: 5, part: 9, hw: 9 },
        'nov-l2': { att: 5, part: 8, hw: 9 },
        'nov-l3': { att: 5, part: 9, hw: 9 },
        'nov-l4': { att: 5, part: 9, hw: 10 },
      },
      s5: {
        'sep-l1': { att: 5, part: 7, hw: 7 },
        'sep-l2': { att: 5, part: 8, hw: 8 },
        'sep-l3': { att: 5, part: 7, hw: 8 },
        'sep-l4': { att: 5, part: 8, hw: 8 },
        'oct-l1': { att: 5, part: 8, hw: 8 },
        'oct-l2': { att: 5, part: 8, hw: 8 },
        'oct-l3': { att: 5, part: 8, hw: 9 },
        'oct-l4': { att: 5, part: 9, hw: 9 },
        'nov-l1': { att: 5, part: 8, hw: 9 },
        'nov-l2': { att: 5, part: 9, hw: 9 },
        'nov-l3': { att: 5, part: 8, hw: 8 },
        'nov-l4': { att: 5, part: 9, hw: 9 },
      },
      s6: {
        'sep-l1': { att: 5, part: 9, hw: 8 },
        'sep-l2': { att: 5, part: 9, hw: 8 },
        'sep-l3': { att: 5, part: 9, hw: 9 },
        'sep-l4': { att: 5, part: 9, hw: 8 },
        'oct-l1': { att: 5, part: 9, hw: 9 },
        'oct-l2': { att: 5, part: 10, hw: 9 },
        'oct-l3': { att: 5, part: 9, hw: 9 },
        'oct-l4': { att: 5, part: 10, hw: 9 },
        'nov-l1': { att: 5, part: 9, hw: 9 },
        'nov-l2': { att: 5, part: 10, hw: 10 },
        'nov-l3': { att: 5, part: 9, hw: 9 },
        'nov-l4': { att: 5, part: 10, hw: 10 },
      },
      s7: {
        'sep-l1': { att: 5, part: 7, hw: 6 },
        'sep-l2': { att: 5, part: 7, hw: 7 },
        'sep-l3': { att: 5, part: 7, hw: 7 },
        'sep-l4': { att: 5, part: 8, hw: 7 },
        'oct-l1': { att: 5, part: 8, hw: 7 },
        'oct-l2': { att: 5, part: 8, hw: 8 },
        'oct-l3': { att: 5, part: 8, hw: 8 },
        'oct-l4': { att: 5, part: 8, hw: 8 },
        'nov-l1': { att: 5, part: 8, hw: 8 },
        'nov-l2': { att: 5, part: 8, hw: 8 },
        'nov-l3': { att: 5, part: 8, hw: 8 },
        'nov-l4': { att: 5, part: 9, hw: 8 },
      },
    },
  },
];
